\ProvidesClass{resume}
\LoadClass[12pt,letterpaper]{article} % Font size and paper type
\usepackage{amsfonts}
\usepackage[colorlinks=true, linkcolor=black, urlcolor=blue, citecolor=black, anchorcolor=black]{hyperref}
\usepackage{soul}
\usepackage{linegoal}
\usepackage{changepage}
\usepackage{ulem}
\newcommand{\bigsize}{\fontsize{12pt}{16pt}\selectfont}
\newcommand{\littlesize}{\fontsize{9pt}{11pt}\selectfont}
\newcommand\tab[1][0.5cm]{\hspace*{#1}}
\newcommand\ttab[1][1cm]{\hspace*{#1}}
\newcommand{\longunderline}[1]{\uline{#1\hfill\mbox{}}}
\usepackage[letterpaper, total={8in, 10.5in}]{geometry}
