\ProvidesClass{resume}
\LoadClass[12pt,letterpaper]{article} % Font size and paper type
\RequirePackage{amsfonts}
\RequirePackage[colorlinks=true, linkcolor=black, urlcolor=blue, citecolor=black, anchorcolor=black]{hyperref}
\RequirePackage{soul}
\RequirePackage{linegoal}
\RequirePackage{changepage}
\RequirePackage{ulem}
\newcommand{\bigsize}{\fontsize{12pt}{16pt}\selectfont}
\newcommand{\littlesize}{\fontsize{9pt}{11pt}\selectfont}
\newcommand\tab[1][0.5cm]{\hspace*{#1}}
\newcommand\ttab[1][1cm]{\hspace*{#1}}
\newcommand{\longunderline}[1]{\uline{#1\hfill\mbox{}}}
\renewcommand{\baselinestretch}{1.05} % Determines line spacing
\RequirePackage[letterpaper, total={8in, 10in}]{geometry}
\pagenumbering{gobble}
